openapi: 3.0.1
info:
  version: 1.0.0
  title: Evian
  description: Documentation for Evian
servers:
  - url: /api/v1
tags:
  - name: Auth
    description: Authentication endpoints
  # - name: User
  #   description: User endpoints
  - name: Station
    description: Station endpoints
  # - name: Order
  #   description: Order endpoints

paths:
  /auth/getUserDetails:
    get:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Get user details
      description: Get user details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserDetailsResponse'
  /station/{stationId}:
    get:
      tags:
        - Station
      summary: Get station details
      description: Get station details
      parameters:
        - name: stationId
          in: path
          description: The id of station whose details is to be retrieved
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStationDetailsResponse'
  /auth/signupUser:
    post:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Signup a new user
      description: Signup a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupUser'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupUserResponse'
  /auth/signupStation:
    post:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Signup a new station
      description: Signup a new station
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupStation'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupStationResponse'
  /station/{state}/{city}:
    get:
      tags:
        - Station
      summary: Get all station details
      description: Get all stations of a particular state and city
      parameters:
        - name: state
          in: path
          description: The state whose stations are to be retrieved
          required: true
          schema:
            type: string
        - name: city
          in: path
          description: The city whose stations are to be retrieved
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllStationDetailsResponse'

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Provide a valid JWT token
  schemas:
    getUserDetailsResponse:
      type: object
      properties:
        email:
          type: string
        createdAt:
          type: object
          properties:
            _seconds:
              type: number
            _nanoseconds:
              type: number
        city:
          type: string
        state:
          type: string
        phone:
          type: string
        name:
          type: string
        profilePicture:
          type: string
    SignupUser:
      type: object
      required:
        - name
        - email
        - state
        - city
      properties:
        name:
          type: string
        phone:
          type: string
        email:
          type: string
        state:
          type: string
        city:
          type: string
    SignupUserResponse:
      type: object
      properties:
        message:
          type: string
    SignupStation:
      type: object
      required:
        - name
        - email
        - address
        - location
        - state
        - city
      properties:
        name:
          type: string
        phone:
          type: string
        email:
          type: string
        address:
          type: string
        location:
          type: string
        state:
          type: string
        city:
          type: string
    SignupStationResponse:
      type: object
      properties:
        message:
          type: string
    getStationDetailsResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        location:
          type: string
        chargingPoints:
          type: array
          items:
            type: object
            properties:
              index:
                type: number
              capacity:
                type: number
              cost:
                type: number
    getAllStationDetailsResponse:
      type: object
      properties:
        stations:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              address:
                type: string
              numberOfChargingPoints:
                type: number
              minCost:
                type: number
              maxCost:
                type: number
